import os
import sys
import time
import re
import google.generativeai as genai
from dotenv import load_dotenv
import speech_recognition as sr
import pyttsx3

# Load environment variables
load_dotenv()

def load_system_prompt():
    try:
        with open("prompts/jack_persona.md", "r", encoding="utf-8") as f:
            return f.read()
    except FileNotFoundError:
        print("Error: prompts/jack_persona.md not found.")
        sys.exit(1)

def init_engine():
    """Initializes the TTS engine with male voice and natural speed."""
    engine = pyttsx3.init()
    
    # Set Rate (Speed) - Default for natural feel
    rate = engine.getProperty('rate')
    engine.setProperty('rate', rate) 
    
    # Set Voice (Male)
    voices = engine.getProperty('voices')
    target_voice = None
    
    # Look for "David" (common Windows male voice) or just "Male"
    for voice in voices:
        if "david" in voice.name.lower() or "male" in voice.name.lower():
            target_voice = voice.id
            break

    if target_voice:
        engine.setProperty('voice', target_voice)
            
    return engine

def speak(text):
    """Speaks the text using a fresh engine instance."""
    try:
        # Clean text for speech: remove markdown symbols and ALL asterisks
        clean_text = re.sub(r'\*.*?\*', '', text)  # Remove *text*
        clean_text = clean_text.replace("*", "")  # Remove any remaining asterisks
        clean_text = clean_text.replace("#", "").replace("- ", "")
        
        print(f"[Debug] Speaking: {clean_text[:50]}...")
        engine = init_engine()
        engine.say(clean_text)
        engine.runAndWait()
        print("[Debug] Speech finished.")
    except Exception as e:
        print(f"Error in TTS: {e}")

def listen():
        except sr.WaitTimeoutError:
            message = "I can't hear you. Could you please repeat that?"
            print(f"Jack: {message}")
            speak(message)
            return None
        except sr.UnknownValueError:
            message = "I didn't catch that. Could you say it again?"
            print(f"Jack: {message}")
            speak(message)
            return None
        except sr.RequestError as e:
            print(f"Could not request results; {e}")
            return None

def load_job_requirements():
    """Loads the job requirements generated by Jill if they exist."""
    try:
        if os.path.exists("job_requirements.md"):
            with open("job_requirements.md", "r", encoding="utf-8") as f:
                return f.read().strip()
    except Exception as e:
        print(f"Warning: Could not read job_requirements.md: {e}")
    return None

def load_cv_input():
    """Loads the candidate's CV from cv_input.txt if it exists, then deletes it."""
    try:
        if os.path.exists("cv_input.txt"):
            with open("cv_input.txt", "r", encoding="utf-8") as f:
                content = f.read().strip()
            
            # Auto-delete to prevent reuse by next user
            try:
                os.remove("cv_input.txt")
                print("✅ Found and loaded cv_input.txt (File deleted for security)")
            except Exception as del_e:
                print(f"⚠️ Loaded cv_input.txt but failed to delete it: {del_e}")
                
            return content
    except Exception as e:
        print(f"Warning: Could not read cv_input.txt: {e}")
    return None

def generate_candidate_profile(chat, job_role=None, cv_content=None):
    """Generates a candidate profile document based on the conversation and optional CV."""
    print("\n📝 Generating Candidate Profile One-Pager...")
    try:
        role_context = f" for the role of {job_role}" if job_role else ""
        
        # Add CV cross-reference if provided
        cv_context = ""
        if cv_content:
            cv_context = f"""

IMPORTANT: The candidate has also provided their CV/Resume. Use this to:
1. Cross-reference factual details (dates, job titles, education)
2. Fill in any gaps from the conversation
3. Validate what they told you
4. Add any additional relevant details they didn't mention

CANDIDATE'S CV:
---
{cv_content}
---

If there are any discrepancies between the conversation and CV, note them in the profile.
"""
        
        prompt =f"""Based on our comprehensive conversation{role_context}, please generate a detailed Candidate Profile One-Pager. 
        {cv_context} 
        
        Include ALL of the following sections:
        - **Professional Summary** (Who they are, years of experience, specialization)
        - **Educational Background** (Degrees, universities, graduation years, certifications, relevant training)
        - **Work Experience Timeline** (List previous roles chronologically with: Company, Title, Duration, Key Responsibilities, Notable Accomplishments, Reason for Leaving)
        - **Current Role & Responsibilities** (What they do day-to-day, current projects)
        - **Key Projects & Achievements** (Specific examples with measurable impact)
        - **Hard Skills & Expertise** (Technical skills, tools, technologies with proficiency levels and years of experience)
        - **Passions & Interests** (What drives them professionally, what excites them)
        - **Target Industries** (Specific industries they're interested in, e.g., fintech, AI, healthcare, climate tech)
        - **Target Companies or Company Types** (e.g., "early-stage startups," "FAANG," "Fortune 500," specific companies mentioned)
        - **Preferred Role Types** (e.g., "hands-on IC," "people manager," "technical lead," "startup vs enterprise")
        - **Industry Insights** (Problems they identified in their industry and how they'd solve them - shows strategic thinking)
        - **Behavioral Traits & Strengths** (Deduced from their scenario responses: teamwork style, leadership capabilities, conflict resolution, handling pressure, problem-solving approach, initiative, learning from failure, resilience)
        - **Cultural Fit Profile** (Ideal work environment, preferred management style, company culture that helps them thrive, dealbreakers/red flags)
        - **Fit for Role** (If a specific role was provided, analyze how well they fit. Otherwise, provide general career guidance and role recommendations)
        - **Salary & Logistics** (Salary expectations with base + bonus breakdown, location preferences, remote/hybrid/on-site preference, availability to start)
        
        CRITICAL: At the very beginning, include a line: "CANDIDATE_NAME: [their full name]"
        
        Format it as a clean, professional Markdown document with clear section headers.
        Be specific and cite examples from our conversation. For behavioral traits, reference the specific scenarios they shared.
        """
        response = chat.send_message(prompt)
        
        # Extract candidate name from response
        content = response.text
        candidate_name = "unknown"
        for line in content.split('\n'):
            if 'CANDIDATE_NAME:' in line:
                candidate_name = line.split('CANDIDATE_NAME:')[1].strip()
                # Remove this line from the content
                content = content.replace(line, "").strip()
                break
        
        # Sanitize name for filename
        import re
        from datetime import datetime
        safe_name = re.sub(r'[^\w\s-]', '', candidate_name.lower())
        safe_name = re.sub(r'[-\s]+', '_', safe_name)
        timestamp = datetime.now().strftime("%Y%m%d_%H%M%S")
        
        # Ensure candidates directory exists
        os.makedirs("candidates", exist_ok=True)
        
        filename = f"candidates/candidate_{safe_name}_{timestamp}.md"
        with open(filename, "w", encoding="utf-8") as f:
            f.write(content)
            
        print(f"✅ Candidate profile saved to {filename}")
        return filename, content
    except Exception as e:
        print(f"❌ Error generating candidate profile: {e}")
        return None, None

def check_for_job_matches(model, candidate_profile_content):
    """Check if candidate matches any available jobs and suggest to Jill."""
    from messaging import get_all_job_specs, send_message
    
    job_files = get_all_job_specs()
    
    if not job_files:
        print("\n📭 No job specs available from Jill yet.")
        return
    
    print(f"\n🔍 Checking candidate against {len(job_files)} available job(s)...")
    
    for job_file in job_files:
        try:
            with open(job_file, "r", encoding="utf-8") as f:
                job_content = f.read()
            
            # Use Gemini to analyze match
            match_prompt = f"""Analyze this candidate profile against the job requirements.
            
CANDIDATE PROFILE:
---
{candidate_profile_content}
---

JOB REQUIREMENTS:
---
{job_content}
---

Provide:
1. Match Score (0.0-1.0, where 1.0 is perfect match)
2. Brief explanation of fit
3. Key strengths for this role
4. Potential gaps or concerns

Format: Start with "MATCH_SCORE: X.XX" then your analysis."""

            response = model.generate_content(match_prompt)
            analysis = response.text
            
            # Extract score
            score_line = [line for line in analysis.split('\n') if 'MATCH_SCORE' in line]
            match_score = 0.0
            if score_line:
                try:
                    match_score = float(score_line[0].split(':')[1].strip())
                except:
                    match_score = 0.5
            
            # Send match suggestion to Jill if score is decent
            if match_score >= 0.6:
                message = f"""🎯 CANDIDATE MATCH SUGGESTION

I think this candidate could be a good fit for the role in {job_file}!

Match Score: {match_score:.2f}/1.0

{analysis}

Let me know if you'd like me to reach out to the candidate about this opportunity!"""

                send_message("Jack", "Jill", "match_suggestion", message, {
                    "candidate_file": "candidate_profile.md",
                    "job_file": job_file,
                    "match_score": match_score
                })
                
                print(f"✅ Sent match suggestion to Jill (Score: {match_score:.2f})")
            else:
                print(f"⚠️  Low match for {job_file} (Score: {match_score:.2f}) - not suggesting")
                
        except Exception as e:
            print(f"Error analyzing match for {job_file}: {e}")


def main():
    api_key = os.getenv("GEMINI_API_KEY")
    if not api_key:
        print("Error: GEMINI_API_KEY not found in environment variables.")
        print("Please create a .env file with your API key.")
        sys.exit(1)

    genai.configure(api_key=api_key)

    system_prompt = load_system_prompt()
    
    # Read messages from Jill
    from messaging import read_messages
    print("\n📬 Checking messages from Jill...")
    messages = read_messages("Jack")
    
    if messages:
        print(f"\n💬 You have {len(messages)} new message(s) from Jill:\n")
        for msg in messages:
            print(f"[{msg['timestamp']}] {msg['type'].replace('_', ' ').title()}:")
            print(f"{msg['content']}\n")
            print("---\n")
    else:
        print("No new messages.\n")
    
    # Check for inputs
    job_requirements = load_job_requirements()
    cv_input = load_cv_input()
    
    # Try to use the specific flash model, fallback or list models on failure
    model_name = "gemini-2.0-flash"
    
    try:
        # Initialize the model
        model = genai.GenerativeModel(
            model_name=model_name,
            system_instruction=system_prompt
        )

        chat = model.start_chat(history=[])
        
        # Build Context Prompt
        context_parts = []
        if job_requirements:
            context_parts.append(f"You are recruiting for this specific role:\n---\n{job_requirements}\n---")
        if cv_input:
            context_parts.append(f"The candidate has provided this CV:\n---\n{cv_input}\n---")
            
        if context_parts:
            context_prompt = "\n".join(context_parts) + "\n\nPlease acknowledge these details. If a CV is provided, ask about specific experiences in it. If a Role is provided, assess their fit for it. Start the conversation naturally."
            print(f"\n📄 Loading Context (Job Specs: {'Yes' if job_requirements else 'No'}, CV: {'Yes' if cv_input else 'No'})...")
            response = chat.send_message(context_prompt)
            intro_text = response.text
        else:
            intro_text = "Hello! I'm Jack. I'm here to help you find your next great role."

        print(f"Jack (Talent Advocate) [{model_name}]: {intro_text}")
        speak(intro_text)

        while True:
            try:
                user_input = listen()
                
                if not user_input:
                    continue

                if user_input.lower() in ['quit', 'exit', 'stop', 'goodbye']:
                    # Check if we already have the CV from start
                    cv_content = cv_input
                    
                    if not cv_content:
                        # Ask for CV upload ONLY if not provided at start
                        cv_request = "Great interview! One more thing - do you have a CV or resume you'd like to share? This will help me create a more accurate profile by cross-referencing what we discussed. If yes, please paste your CV text into a file called 'candidate_cv.txt' in this directory and then say 'ready'. If not, just say 'no' or 'skip'."
                        print(f"\nJack: {cv_request}")
                        speak(cv_request)
                        
                        # Wait for response
                        cv_response = listen()
                        
                        if cv_response and cv_response.lower() in ['ready', 'yes', 'done', 'uploaded']:
                            # Try to read CV
                            if os.path.exists("candidate_cv.txt"):
                                try:
                                    with open("candidate_cv.txt", "r", encoding="utf-8") as f:
                                        cv_content = f.read()
                                    confirm_msg = "Thanks! I've got your CV. I'll use this to cross-reference our conversation."
                                    print(f"\nJack: {confirm_msg}")
                                    speak(confirm_msg)
                                    
                                    # Delete CV file immediately to prevent reuse
                                    os.remove("candidate_cv.txt")
                                    print("✅ CV processed and file deleted")
                                except Exception as e:
                                    print(f"⚠️ Couldn't read CV file: {e}")
                            else:
                                wait_msg = "I don't see the candidate_cv.txt file yet. Let me know when it's ready by saying 'ready'."
                                print(f"\nJack: {wait_msg}")
                                speak(wait_msg)
                                
                                # Give one more chance
                                second_response = listen()
                                if second_response and os.path.exists("candidate_cv.txt"):
                                    try:
                                        with open("candidate_cv.txt", "r", encoding="utf-8") as f:
                                            cv_content = f.read()
                                        os.remove("candidate_cv.txt")
                                        print("✅ CV processed and file deleted")
                                    except:
                                        pass
                    
                        if not cv_content:
                            no_cv_msg = "No problem! I'll create your profile based on our conversation."
                            print(f"\nJack: {no_cv_msg}")
                            speak(no_cv_msg)
                    
                    # Generate Profile with optional CV cross-reference
                    result = generate_candidate_profile(chat, job_role="Target Role" if job_requirements else None, cv_content=cv_content)
                    
                    if result and result[0]:
                        filename, profile_content = result
                        
                        # Approval loop - allow iterative refinement
                        while True:
                            # Show the document to user (don't read it aloud)
                            print("\n" + "="*60)
                            print("📄 CANDIDATE PROFILE GENERATED")
                            print("="*60)
                            print(profile_content)
                            print("="*60)
                            
                            # Ask for approval
                            approval_message = "I've generated your candidate profile above. Please review it. Would you like me to save this and share it with Jill? Say 'yes' to approve or 'no' if you want changes."
                            print(f"\nJack: {approval_message}")
                            speak(approval_message)
                            
                            # Wait for approval
                            approval = listen()
                            
                            if approval and approval.lower() in ['yes', 'yeah', 'yep', 'sure', 'approve', 'good', 'looks good', 'perfect']:
                                # Save and share
                                from messaging import send_message
                                
                                # Overwrite file with latest content
                                with open(filename, "w", encoding="utf-8") as f:
                                    f.write(profile_content)
                                
                                send_message("Jack", "Jill", "candidate_profile", 
                                           f"I've just completed an interview and built a candidate profile. Check out {filename}!",
                                           {"candidate_file": filename})
                                
                                print(f"📤 Sent candidate profile to Jill")
                                
                                # Check for matches
                                check_for_job_matches(model, profile_content)
                                
                                success_msg = "Great! I've saved your profile and shared it with Jill. She'll match you with suitable opportunities. Best of luck, and goodbye!"
                                print(f"\nJack: {success_msg}")
                                speak(success_msg)
                                break  # Exit approval loop
                            else:
                                # Ask for changes
                                changes_msg = "No problem! What would you like me to change or add to your profile?"
                                print(f"\nJack: {changes_msg}")
                                speak(changes_msg)
                                
                                # Get user feedback
                                feedback = listen()
                                
                                if not feedback:
                                    continue
                                
                                # Generate updated version
                                update_prompt = f"""The candidate wants changes to their profile. Here's the current version:

---
{profile_content}
---

Candidate feedback: {feedback}

Please generate an UPDATED version incorporating their feedback. Keep the same format and structure, but make the requested changes. Include the "CANDIDATE_NAME: [name]" line at the beginning."""

                                print("\n🔄 Updating candidate profile...")
                                update_response = chat.send_message(update_prompt)
                                
                                # Extract updated content
                                updated_content = update_response.text
                                for line in updated_content.split('\n'):
                                    if 'CANDIDATE_NAME:' in line:
                                        updated_content = updated_content.replace(line, "").strip()
                                        break
                                
                                profile_content = updated_content
                                print("✅ Updated!")
                                # Loop back to show updated version
                    else:
                        error_msg = "I had trouble generating your profile. Let me know if you'd like to try again. Goodbye!"
                        print(f"Jack: {error_msg}")
                        speak(error_msg)
                    break  # Exit main conversation loop

                response = chat.send_message(user_input)
                print(f"\nJack: {response.text}")
                speak(response.text)

            except KeyboardInterrupt:
                print("\nJack: Goodbye!")
                break
            except Exception as e:
                print(f"\nAn error occurred during chat: {e}")

    except Exception as e:
        print(f"\nError initializing model '{model_name}': {e}")
        print("\nListing available models...")
        try:
            with open("models.txt", "w") as f:
                for m in genai.list_models():
                    if 'generateContent' in m.supported_generation_methods:
                        print(f"- {m.name}")
                        f.write(f"{m.name}\n")
            print("Models written to models.txt")
        except Exception as list_e:
            print(f"Could not list models: {list_e}")
        print("\nPlease update the 'model_name' in jack_agent.py to one of the available models above.")

if __name__ == "__main__":
    main()
